CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE film (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  realisateur TEXT NOT NULL,
  date_sortie DATE NOT NULL,
  synopsis TEXT NOT NULL,

  FOREIGN KEY (author_id) REFERENCES user (id)
);

